server:
  port: 8200

spring:
  application:
    name: image-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/photos_db
    username: root
    password: 123456

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
# Log SQL
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
